var GAME_LEVELS = [
  ["yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "   yyyyy       y y   y y  y y y  y y  y y y  y y  y  yy y yyy y  y y y y   y y y",
   "   y   yy     y   y y    y    y     y        y     y  y   yy   y          y     ",
   "                                                                                ",
   "                                                                      x         ",
   "                                                                      x         ",
   "                                                                      x         ",
   "                                                                      xx        ",
   "                                                            xxxxx     xxxxx     ",
   "     x                                                     x               x    ",
   "    x                                o                    x                 x   ",
   "   x                                xxx                  x                   x  ",
   "  x                              o                   xxxx                   dx  ",
   "  x              xxxxxxx        xxx               o                          x  ",
   "  x              x                        xxxxxxxxxx                         x  ",
   "  x          xxxxx     o   xxxx                                              x  ",
   "!!x  @       x         x   x                                  xxxx   xx  x o x  ",
   "!!xxxxxxxxxxxx!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!xxxxx!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "                                                ",
   "   x                                            ",
   "  x                                             ",
   " x                                              ",
   "x                                               ",
   "x                      dxxxxxxxxxxxxxxxxxx      ",
   "x                      dxxxxx!!!!v!!!!!!!x      ",
   "xx  xx                 dxxxxx!!!! !!!!!!!x      ",
   "x   xx @ o             dxxx              x      ",
   "x  xxxxxxxxxxxxxxxxxxxxxx                x      ",
   "x                                        x      ",
   "xx                                       x      ",
   "x                      o      p o pp   o x      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxx      ",
   "                                xxx             ",
   "                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "       x x                                                                      ",
   "                                                                                ",
   "      x   x                                                                     ",
   "       xxx                                                                      ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  @                                                                             ",
   " xxx                                                                            ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
